apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s.name" . }}
  labels:
    {{- include "k8s.labels" . | nindent 4 }}
spec:
  {{- if and (not .Values.autoscaling.enabled) (not (contains "production" .Release.Namespace)) }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "k8s.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- if and .Values.vault.agentInject.enabled (or (contains "production" .Release.Namespace) (contains "staging" .Release.Namespace)) }}
        {{- include "k8s.vaultAgentInjectPodAnnotations" . | nindent 8 }}
        {{- end -}}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "k8s.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if and .Values.serviceAccount.create (not (contains "development" .Release.Namespace)) }}
      serviceAccountName: {{ include "k8s.serviceAccountName" . }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.env }}
          {{- range $key, $value := . }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.internalPort }}
              protocol: TCP
          {{- if .Values.probes.enabled -}}
          {{- with .Values.probes.liveness }}
          livenessProbe:
            httpGet:
              path: {{ $.Values.probes.path }}
              port: {{ $.Values.service.internalPort }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.probes.readiness }}
          readinessProbe:
            httpGet:
              path: {{ $.Values.probes.path }}
              port: {{ $.Values.service.internalPort }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      nodeSelector:
        {{- include "k8s.deploymentTolerations" . | nindent 8 }}
      tolerations:
        {{- $tolerations := include "k8s.deploymentTolerations" . | fromYaml }}
        {{- range $key, $value := $tolerations }}
        - key: {{ $key | quote }}
          operator: "Equal"
          value: {{ $value | quote }}
          effect: "NoSchedule"
        {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
