apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s.serviceName" . }}
  labels:
    {{- include "k8s.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "k8s.selectorLabels" . | nindent 4 }}
---
{{- if or (contains "development" .Release.Namespace) (contains "staging" .Release.Namespace) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ExternalName
  externalName: {{ .Values.service.externalName }}
{{- end }}
