/**
 * Upserts products from scripts/hna-products.json (generated by extractHnaProducts.py)
 * into the Product table.
 *
 * Usage:
 *   npx tsx scripts/importHnaProducts.ts
 */
import "dotenv/config";
import path from "path";
import fs from "fs";
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();
const NOW = new Date().toISOString();
const BATCH = 200;

interface HnaProduct {
  kodeProduk: string;
  namaProduk: string;
  namaGroupBrand: string;
  hna: number;
  satuan: string;
  zatAktif: string | null;
}

function esc(v: string | null | undefined): string {
  if (v == null) return "NULL";
  return `'${String(v).replace(/'/g, "''")}'`;
}

function chunks<T>(arr: T[], size: number): T[][] {
  const out: T[][] = [];
  for (let i = 0; i < arr.length; i += size) out.push(arr.slice(i, i + size));
  return out;
}

async function main() {
  const jsonPath = path.resolve("scripts/hna-products.json");
  if (!fs.existsSync(jsonPath)) {
    console.error("hna-products.json not found. Run: python scripts/extractHnaProducts.py");
    process.exit(1);
  }

  const products: HnaProduct[] = JSON.parse(fs.readFileSync(jsonPath, "utf-8"));
  console.log(`Upserting ${products.length} products...`);

  for (const batch of chunks(products, BATCH)) {
    const vals = batch.map((p) =>
      `(${esc(p.kodeProduk)},${esc(p.namaGroupBrand)},${esc(p.namaProduk)},${esc(p.zatAktif)},${esc(p.satuan)},${p.hna},'${NOW}','${NOW}','${NOW}')`
    ).join(",");

    await prisma.$executeRawUnsafe(`
      INSERT INTO "Product" ("kodeProduk","namaGroupBrand","namaProduk","zatAktif",satuan,hna,"syncedAt","createdAt","updatedAt")
      VALUES ${vals}
      ON CONFLICT ("kodeProduk") DO UPDATE SET
        "namaGroupBrand" = EXCLUDED."namaGroupBrand",
        "namaProduk"     = EXCLUDED."namaProduk",
        satuan           = EXCLUDED.satuan,
        hna              = EXCLUDED.hna,
        "syncedAt"       = EXCLUDED."syncedAt",
        "updatedAt"      = EXCLUDED."updatedAt"
    `);
  }

  const total = await prisma.product.count();
  console.log(`Done. Product table now has ${total} rows.`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
